import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navigation from '@/components/layout/navigation'
import NavigationMobile from '@/components/layout/navigationMobile'
import Footer from '@/components/layout/footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="hidden lg:block">
        <Navigation/>
        </div>
        <div className="block lg:hidden">
        <NavigationMobile/>
        </div>
      
      <div className=" mx-[10%]">
      {children}  
      </div>
      <Footer/>
      </body>
    </html>
  );
}
